name       : font-firago
version    : 1.000
release    : 1
source     :
    - https://github.com/bBoxType/FiraGO/archive/1.000.tar.gz : b2f97f1ee02921ca1776903fa0e6f1358b017bf854c0e8776b6b8512e3c9d4a1
license    : OFL-1.1
component  : desktop.font
summary    : An independent Open Source typeface — FiraGO
description: |
    An independent Open Source typeface — FiraGO
install    : |
    for cat in Italic Roman; do
        install -D -m00644 Fonts/FiraGO_OTF/${cat}/*.otf -t $installdir/usr/share/fonts/opentype/firago/
        install -D -m00644 Fonts/FiraGO_TTF/${cat}/*.ttf -t $installdir/usr/share/fonts/truetype/firago/
    done
